[manager]
show_hidden = true
sort_sensitive = true
sort_dir_first = true
sort_by = "natural"
show_symlink = true

[preview]
tab_size = 2

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]
