[general]
import = [
"~/.config/alacritty/CURRENT_THEME.toml",
"~/.config/alacritty/keyboard.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 140, lines = 50 }
padding = { x = 20, y = 10 }
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 18

[cursor]
style = { shape = "Beam", blinking = "Always" }
vi_mode_style = { shape = "Beam", blinking = "Always" }
unfocused_hollow = false
